import { Component, OnInit } from "@angular/core";

@Component({
  selector: "app-input-button-unit",
  templateUrl: "./input-button-unit.component.html",
  styleUrls: ["./input-button-unit.component.css"]
})
export class InputButtonUnitComponent implements OnInit {
  constructor() {this.changeTitle("This is the contructor")}

  ngOnInit() {


    this.changeTitle("this is change title")
  }
  title = "Welcome!";
  changeTitle(newTitle: string) {
  this.title = newTitle;
}
generateTitle(): string {
  return 'This title was generated by a method.';
}

}
